# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemperNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='thumbnail_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
