# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SemperNewsApp', '0002_auto_20171213_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('newsItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SemperNewsApp.NewsItem')),
                ('subtext', models.CharField(max_length=511)),
            ],
        ),
    ]
