# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SemperNewsApp', '0005_auto_20171224_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='Journalist', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='featureditem',
            name='newsItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SemperNewsApp.NewsItem'),
        ),
    ]
